location /api/ {
    alias /var/www/cmetaxonomy.org/docs/api/;
    default_type application/json;

    add_header Access-Control-Allow-Origin  "*" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Accept, Content-Type" always;
    add_header Cache-Control "public, max-age=300" always;

    if ($request_method = OPTIONS) {
        return 204;
    }
}
